Anul 2/Sem 2/Web/WebApplication1/WebApplication1/Models/Card.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class Card
    {
        public Guid Id { get; set; }

        public string Number { get; set; }

        public Card()
        {
            Id = Guid.NewGuid();
            Number = "";
        }
        public Card(string number)
        {
            Id = Guid.NewGuid();
            Number = number;
        }
    }
}

Anul 2/Sem 2/Web/WebApplication1/WebApplication1/Models/ErrorViewModel.cs
using System;

namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Anul 2/Sem 2/Web/WebApplication1/WebApplication1/Models/UserViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models
{
    public class UserViewModel
    {
        [Required]
        public string Username { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

    }
}

Anul 2/Sem 2/Web/WebApplication1/WebApplication1/Controllers/CardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CardsController : Controller
    {
        public CardsController()
        {
        }

        // GET: Cards
        public ActionResult Index()
        {
            return View(WebApplication1.Shared.DB.cards);
        }

        // GET: Cards/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var card = WebApplication1.Shared.DB.cards.FirstOrDefault(m => m.Id == id);
            if (card == null)
            {
                return NotFound();
            }

            return View(card);
        }

        // GET: Cards/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cards/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("Id,Number")] Card card)
        {
            if (ModelState.IsValid)
            {
                card.Id = Guid.NewGuid();
                WebApplication1.Shared.DB.cards.Add(card);
                return RedirectToAction(nameof(Index));
            }
            return View(card);
        }

        // GET: Cards/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var card = WebApplication1.Shared.DB.cards.Find(c=> c.Id == id);
            if (card == null)
            {
                return NotFound();
            }
            return View(card);
        }

        // POST: Cards/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Guid id, [Bind("Id,Number")] Card card)
        {
            Console.WriteLine(card.Number);
            if (id != card.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    int i = WebApplication1.Shared.DB.cards.FindIndex(c => c.Id == id);
                    Card car = new Card(card.Number);
                    car.Id = id;
                    WebApplication1.Shared.DB.cards[i] = car;
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CardExists(card.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(card);
        }

        // GET: Cards/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var card = WebApplication1.Shared.DB.cards.Find(c => c.Id == id);

            if (card == null)
            {
                return NotFound();
            }

            return View(card);
        }

        // POST: Cards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            var card = WebApplication1.Shared.DB.cards.Find(c => c.Id == id);
            WebApplication1.Shared.DB.cards.Remove(card);
            return RedirectToAction(nameof(Index));
        }

        private bool CardExists(Guid id)
        {
            return WebApplication1.Shared.DB.cards.Any(e => e.Id == id);
        }
    }
}

Anul 2/Sem 2/Web/WebApplication1/WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Anul 2/Sem 2/Web/WebApplication1/WebApplication1/Controllers/UserController.cs
using System;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Views.Shared
{
    public class UserController : Controller
    {
        
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(Models.UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = WebApplication1.Shared.DB.Login(model.Username, model.Password);
                if (user != null)
                {
                    WebApplication1.Shared.DB.LogIn(user);
                    return RedirectToAction("Dashboard");
                }
            }
            ViewData["message"] = "Username or password is incorrect. Please try again.";
            return View();
        }
        public ActionResult Logout()
        {
            WebApplication1.Shared.DB.Logout();
            return RedirectToAction("Index", "Home");
        }


        public ActionResult Dashboard()
        {
            if(WebApplication1.Shared.DB.isLogined==false)
                return RedirectToAction("Index","Home");

            return View();
        }
    }
}

Anul 2/Sem 2/Web/WebApplication1/WebApplication1/Views/Cards/Create.cshtml
@model WebApplication1.Models.Card

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Card</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Anul 2/Sem 2/Web/WebApplication1/WebApplication1/Views/Cards/Delete.cshtml
@model WebApplication1.Models.Card

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Card</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Anul 2/Sem 2/Web/WebApplication1/WebApplication1/Views/Cards/Details.cshtml
@model WebApplication1.Models.Card

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Card</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Anul 2/Sem 2/Web/WebApplication1/WebApplication1/Views/Cards/Edit.cshtml
@model WebApplication1.Models.Card

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Card</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Delete" asp-route-id="@Model.Id">Delete</a> | 
    <a asp-controller="Cards" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Anul 2/Sem 2/Web/WebApplication1/WebApplication1/Views/Cards/Index.cshtml
@model IEnumerable<WebApplication1.Models.Card>

@{
    ViewData["Title"] = "Index";
}
<h2>All cards</h2>
<p>
    <a asp-controller="Cards" asp-action="Create">Create New</a>
</p>
@{
    
    for (int i = 0; i < WebApplication1.Shared.DB.cards.Count; i++)
    {
       Card card = WebApplication1.Shared.DB.cards[i];
        <div class="card" asp-controller="Card" asp-action="Edit" @{if (i % 2 == 0) { Write("style=background-color:#EF3E5C"); } }>
            <div class="card_number">
                <p>@card.Number</p>
            </div>
            <div class="card_holder">
                <p>C David</p>
                <p>01/22</p>
            </div>
            <div class="card_icon">
                <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/217538/discover-curved-64px.png">
            </div>
            <a class="card_edit" asp-action="Edit" asp-route-id="@card.Id">Edit</a>
        </div>
    }
}

Anul 2/Sem 2/Web/WebApplication1/WebApplication1/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Anul 2/Sem 2/Web/WebApplication1/WebApplication1/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Anul 2/Sem 2/Web/WebApplication1/WebApplication1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Anul 2/Sem 2/Web/WebApplication1/WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        
    </environment>
    <style>
        body {
            margin: 0;
            color: #edf3ff;
            background: #c8c8c8;
            background: url(https://hdqwalls.com/download/material-design-4k-2048x1152.jpg) fixed;
            background-size: cover;
            font: 600 16px/18px 'Open Sans',sans-serif;
        }

        :after, :before {
            box-sizing: border-box
        }

        .clearfix:after, .clearfix:before {
            content: '';
            display: table
        }

        .clearfix:after {
            clear: both;
            display: block
        }

        a {
            color: inherit;
            text-decoration: none
        }


        .hr {
            height: 2px;
            margin: 60px 0 50px 0;
            background: rgba(255,255,255,.2);
        }

        .foot-lnk {
            text-align: center;
        }
    </style>
    <style>
        .card {
            background: #ff5722;
            border-radius: 5px;
            width: 280px;
            height: 160px;
            margin: 1em;
            display: inline-flex;
            -webkit-box-pack: justify;
            -ms-flex-pack: justify;
            justify-content: space-between;
            -webkit-box-align: center;
            -ms-flex-align: center;
            align-items: center;
            padding: 1em;
            -webkit-box-orient: horizontal;
            -webkit-box-direction: normal;
            -ms-flex-flow: row wrap;
            flex-flow: row wrap;
            cursor: pointer;
            z-index: 1;
            position: relative;
            -webkit-transition: all ease .45s;
            transition: all ease .45s;
        }
        .card:before {
            content: '';
            background: url(http://speckycdn.sdm.netdna-cdn.com/wp-content/uploads/2012/10/world_map_06.jpg);
            opacity: 0.2;
            -webkit-transform: translateX(-16px);
            transform: translateX(-16px);
            border-radius: 5px;
            width: 100%;
            height: 100%;
            background-size: cover;
            position: absolute;
            z-index: -100;
        }
        .card_number, .app_inner aside .wallet .card_holder > p {
            font-size: 20px;
            color: #FFF;
        }
        .card_holder {
            width: 50%;
        }
        .card_number {
            width: 100%;
        }
        .card_icon {
            width: 20%;
        }
        .card_icon > img {
            width: 35px;
            height: auto;
        }
        .card_edit{
            width:100%;
        }
        .card_edit:hover {
            color: lightgoldenrodyellow !important;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WebApplication1</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    @{
                        if (WebApplication1.Shared.DB.isLogined)
                        {
                            <li><a asp-area="" asp-controller="User" asp-action="Dashboard">Dashboard</a></li>
                            <li><a asp-area="" asp-controller="Cards" asp-action="Index">Cards</a></li>
                            <li><a asp-area="" asp-controller="User" asp-action="Logout">Log out</a></li>
                        }
                        else
                        {
                            <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                            <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                            <li><a asp-area="" asp-controller="User" asp-action="Login">Login</a></li>
                        }
                    }
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - WebApplication1</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Anul 2/Sem 2/Web/WebApplication1/WebApplication1/Views/User/Dashboard.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h2><i>Welcome back,</i>  @{ Write(WebApplication1.Shared.DB.loginedUser.Name); }</h2>
<h4>Latest used:</h4>
@{
    for (int i = 0; i < WebApplication1.Shared.DB.cards.GetRange(0,3).Count; i++)
    {
        Card card = WebApplication1.Shared.DB.cards.GetRange(0, 3)[i];
        <div class="card" @{if (i % 2 == 0) { Write("style=background-color:#EF3E5C"); } }>
            <div class="card_number">
                <p >@card.Number</p>
            </div>
            <div class="card_holder">
                <p >C David</p>
                <p >01/22</p>
            </div>
            <div class="card_icon">
                <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/217538/discover-curved-64px.png">
            </div>
        </div>
    }
}

Anul 2/Sem 2/Web/WebApplication1/WebApplication1/Views/User/Login.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<style>

    .login-wrap {
        max-width: 500px;
        width: 100%;
        margin: 10vh auto;
        position: relative;
        background: url(https://maxcdn.icons8.com/app/uploads/2016/03/material-1-1000x563.jpg) no-repeat center;
        background-size: cover;
        box-shadow: 0 12px 15px 0 rgba(0,0,0,.24),0 17px 50px 0 rgba(0,0,0,.19);
    }

    .login-html {
        width: 100%;
        height: 100%;
        padding: 30px 50px 70px;
        background: rgba(0,0,0,0.5);
    }

    .login-form .group .label,
    .login-form .group .button {
        text-transform: uppercase;
    }

    .login-form .group {
        margin-bottom: 15px;
    }

        .login-form .group .label,
        .login-form .group .input,
        .login-form .group .button {
            width: 100%;
            color: #fff;
            display: block;
        }

        .login-form .group .input,
        .login-form .group .button {
            border: none;
            padding: 15px 20px;
            border-radius: 25px;
            background: rgba(255,255,255,.1);
        }

        .login-form .group .button {
            background: #1161ee;
        }
</style>


@model WebApplication1.Models.UserViewModel
@{
    using (Html.BeginForm("Login", "User", FormMethod.Post))
    {
        <div class="login-wrap">
            <div class="login-html">
                @{
                    if (ViewData.ContainsKey("message"))
                    {
                        <div class="alert alert-danger" role="alert">
                            @ViewData["message"]
                        </div>
                    }
                        }
                        <h1 style="text-align:center;margin-bottom:64px">Login</h1>
                        <div class="login-form">
                            <div class="sign-in-htm">

                                <div class="group">
                                    <label for="user" class="label">Username</label>
                                    @Html.TextBoxFor(m => m.Username, new { @class = "input" })
                                </div>
                                <div class="group">
                                    <label for="pass" class="label">Password</label>
                                    @Html.PasswordFor(m => m.Password, new { @class = "input" })
                                </div>
                                <div class="group">
                                    <input type="submit" class="button" value="Sign In">
                                </div>
                            </div>
                        </div>
                    </div>
        </div>

    }
}